------------------------------------------------------------------
-- |
-- Module      :  Data.Plastic.GraphPrim
-- Copyright   :  (c) Dmitry Golubovsky, 2011
-- License     :  BSD-style
-- 
-- Maintainer  :  golubovsky@gmail.com
-- Stability   :  experimental
-- Portability :  GHC >= 6.12.2
-- 
--
--
-- Graphics primitive commands generated by Plastic objects
------------------------------------------------------------------

module Data.Plastic.GraphPrim (
  GraphPrim (..)
) where

data GraphPrim = GraphPrim

